---
server: true
markdown: maruku
auto: true
cities:
- albuquerque:
    name: Albuquerque, NM
    latitude: 35.110703
    longitude: -106.609991
- atlanta:
    name: Atlanta, GA
    latitude: 33.7489954
    longitude: -84.3879824
- austin:
    name: Austin, TX
    latitude: 30.267153
    longitude: -97.7430608
- baltimore:
    name: Baltimore, MD
    latitude: 39.281633
    longitude: -76.5811712
- bangalore:
    name: Bangalore, India
    latitude: 12.9715987
    longitude: 77.5945627
- beijing:
    name: Beijing, China
    latitude: 39.90403
    longitude: 116.407526
- bellingham:
    name: Bellingham, WA
    longitude: -122.5100717
    latitude: 48.7618795
- bend:
    name: Bend, OR
    latitude: 44.053125
    longitude: -121.318132
- berlin:
    name: Berlin, Germany
    latitude: 52.519171
    longitude: 13.4060912
- birmingham:
    name: Birmingham, AL
    latitude: 33.5206608
    longitude: -86.80248999999999
- boise:
    name: Boise, ID
    latitude: 43.589235
    longitude: -116.256917
- boston:
    name: Boston, MA
    latitude: 42.3584308
    longitude: -71.0597732
- bristol:
    name: Bristol, UK
    latitude: 51.4522387
    longitude: -2.5900163
- brussels:
    name: Brussels, Belgium
    latitude: 50.8503396
    longitude: 4.3517103
- buffalo:
    name: Buffalo, NY
    latitude: 42.88644679999999
    longitude: -78.8783689
- calgary:
    name: Calgary, AB
    latitude: 51.0419341
    longitude: -114.0360957
- caracas:
    name: Caracas, Distrito Capital
    latitude: 10.5004352
    longitude: -66.9511459
- chicago:
    name: Chicago, IL
    latitude: 41.8781136
    longitude: -87.6297982
- cincinnati:
    name: Cincinnati, OH
    latitude: 39.102945
    longitude: -84.508684
- cleveland:
    name: Cleveland, OH
    latitude: 41.510845
    longitude: -81.567016
- columbia:
    name: Columbia, SC
    latitude: 34.0007104
    longitude: -81.0348144
- columbus:
    name: Columbus, OH
    latitude: 39.9611755
    longitude: -82.99879419999999
